subinclude("//build_defs:python")

python_binary(
    name = "verify_dist_deps",
    main = "verify_dist_deps.py",
    visibility = ["PUBLIC"],
    deps = [
        "//third_party/python:packaging",
    ],
)
